version: '3'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    command: >
      sh -c "
      rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange;
      rabbitmq-server"

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    depends_on:
      - rabbitmq

  geatway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: npm run start:dev gateway
    depends_on:
      - rabbitmq
      - postgres

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    depends_on:
      - postgres
      - rabbitmq

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
    command: npm run start:dev notifications
    env_file:
      - ./apps/users/.env
    depends_on:
      - postgres
      - rabbitmq